Script started on 2017年03月17日 (週五) 20時36分30秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m  git config -l
user.email=t91cs1522yu@gmail.com
user.name=larvavared
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/larvavared/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=lab1
branch.master.merge=refs/heads/master
remote.lab1.url=https://github.com/larvavared/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
remote.lab1.script.url=https://github.com/larvavared/lab1.git
remote.lab1.script.fetch=+refs/heads/*:refs/remotes/lab1.script/*
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m  git clone https://github.com/larvavared/la b1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月17日 (週五) 20時36分56秒
